### ISSUE TITLE
Color light (Wemos D1 mini with neopixel) has no brightness property

### ISSUE THREAD

**Issue by Catalin84** [tim-hellhake/tasmota-adapter#25]
Hi i use Wemos D1 R1 mini with Neopixel led band.
Works OK BUT, i dont have dimmer button.
![image](https://user-images.githubusercontent.com/57527589/77076115-084a8d00-69fc-11ea-9c9a-fa153d67f6f5.png)
![image](https://user-images.githubusercontent.com/57527589/77076164-18626c80-69fc-11ea-9515-c11619507ac2.png)
![image](https://user-images.githubusercontent.com/57527589/77076255-3b8d1c00-69fc-11ea-91e7-824ebe1e8dc5.png)
There is a problem with my config?

**Comment by tim-hellhake** [comment]
That's actually intended.
There were a lot of discussions in the IoT team on how to handle color bulbs.
You can read parts of it here: https://github.com/mozilla-iot/gateway/issues/1378.
Because a lot of users asked for it, this will change in release 0.12.
I'm currently working on adding support for it.
As I have no RGB hardware, I would be happy if you could test it for me.

**Comment by Catalin84** [comment]
I can test it. Let me know when i can.

**Comment by tim-hellhake** [comment]
The update introduces a new experimental option for the color mode.
If you activate it you should see a brightness property on your color device.
As soon as the PR is merged you can test it.
Please let me know if everything works.

**Comment by tim-hellhake** [comment]
@Catalin84 Did you have a chance to test it?

**Comment by tim-hellhake** [comment]
@off-my-lawn Fyi

**Comment by tim-hellhake** [comment]
@Catalin84
I'm closing this now.
Feel free to open a new issue if something is not working.
